In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("C:/Users/DITU/Desktop/train.csv")

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
5,False,False,False,False,False,True,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,True,False
8,False,False,False,False,False,False,False,False,False,False,True,False
9,False,False,False,False,False,False,False,False,False,False,True,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,True,False
13,False,False,False,False,False,False,False,False,False,False,True,False
14,False,False,False,False,False,False,False,False,False,False,True,False
15,False,False,False,False,False,False,False,False,False,False,True,False
16,False,False,False,False,False,False,False,False,False,False,True,False
17,False,False,False,False,False,True,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False,False,False,True,False
19,False,False,False,False,False,True,False,False,False,False,True,False
20,False,False,False,False,False,False,False,False,False,False,True,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,True,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,True,False
25,False,False,False,False,False,False,False,False,False,False,True,False
26,False,False,False,False,False,True,False,False,False,False,True,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,True,False,False,False,False,True,False
29,False,False,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
861,False,False,False,False,False,False,False,False,False,False,True,False
862,False,False,False,False,False,False,False,False,False,False,False,False
863,False,False,False,False,False,True,False,False,False,False,True,False
864,False,False,False,False,False,False,False,False,False,False,True,False
865,False,False,False,False,False,False,False,False,False,False,True,False
866,False,False,False,False,False,False,False,False,False,False,True,False
867,False,False,False,False,False,False,False,False,False,False,False,False
868,False,False,False,False,False,True,False,False,False,False,True,False
869,False,False,False,False,False,False,False,False,False,False,True,False
870,False,False,False,False,False,False,False,False,False,False,True,False
871,False,False,False,False,False,False,False,False,False,False,False,False
872,False,False,False,False,False,False,False,False,False,False,False,False
873,False,False,False,False,False,False,False,False,False,False,True,False
874,False,False,False,False,False,False,False,False,False,False,True,False
875,False,False,False,False,False,False,False,False,False,False,True,False
876,False,False,False,False,False,False,False,False,False,False,True,False
877,False,False,False,False,False,False,False,False,False,False,True,False
878,False,False,False,False,False,True,False,False,False,False,True,False
879,False,False,False,False,False,False,False,False,False,False,False,False
880,False,False,False,False,False,False,False,False,False,False,True,False
881,False,False,False,False,False,False,False,False,False,False,True,False
882,False,False,False,False,False,False,False,False,False,False,True,False
883,False,False,False,False,False,False,False,False,False,False,True,False
884,False,False,False,False,False,False,False,False,False,False,True,False
885,False,False,False,False,False,False,False,False,False,False,True,False
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [12]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
df=df.dropna()

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x=df[['Age','Fare']]
y=df['Survived']

In [24]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [27]:
from sklearn.linear_model import LogisticRegression

In [29]:
lr=LogisticRegression()
lr.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [31]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [39]:
y_predict = lr.predict(x_test)
accuracy_score(y_predict,y_test)

0.6229508196721312

In [41]:
a = np.array([[6,26.550]])
lr.predict(a)

array([1], dtype=int64)